# Generated by Django 4.2.7 on 2025-07-03 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('topic', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.coursegroup')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.schedule')),
            ],
            options={
                'unique_together': {('course_group', 'schedule', 'date')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_sessions', models.IntegerField(default=0)),
                ('present_count', models.IntegerField(default=0)),
                ('absent_count', models.IntegerField(default=0)),
                ('late_count', models.IntegerField(default=0)),
                ('excused_count', models.IntegerField(default=0)),
                ('attendance_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('course_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.coursegroup')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.studentprofile')),
            ],
            options={
                'unique_together': {('student', 'course_group', 'period_start', 'period_end')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Presente'), ('absent', 'Ausente'), ('late', 'Tardanza'), ('excused', 'Justificada')], max_length=10)),
                ('arrival_time', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('marked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='attendance.attendancesession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.studentprofile')),
            ],
            options={
                'unique_together': {('session', 'student')},
            },
        ),
    ]
