name: fine_tune_english
description: Aplicación móvil para Fine Tune English - Sistema de gestión educativa
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # HTTP & API
  dio: ^5.3.2

  # Local Storage
  shared_preferences: ^2.2.2

  # UI Components
  cached_network_image: ^3.3.0

  # Image Picker
  image_picker: ^1.0.4

  # File handling
  path_provider: ^2.1.1

  # Utilities
  intl: ^0.18.1
  url_launcher: ^6.2.1

  # Charts
  fl_chart: ^0.65.0

  # Dependency Injection
  get_it: ^7.6.4

  # State Management
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2

  # Routing
  go_router: ^12.1.1

  # JSON Serialization
  json_annotation: ^4.8.1

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

  # Linting
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

    - family: Coolvetica
      fonts:
        - asset: assets/fonts/Coolvetica.ttf