# Generated by Django 4.2.7 on 2025-07-03 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('capacity', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('equipment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
                ('level', models.CharField(choices=[('A1', 'Principiante A1'), ('A2', 'Principiante A2'), ('B1', 'Intermedio B1'), ('B2', 'Intermedio B2'), ('C1', 'Avanzado C1'), ('C2', 'Avanzado C2')], max_length=2)),
                ('modality', models.CharField(choices=[('presencial', 'Presencial'), ('virtual', 'Virtual'), ('hibrido', 'Híbrido')], max_length=20)),
                ('duration_weeks', models.IntegerField()),
                ('hours_per_week', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('max_students', models.IntegerField(default=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('course_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.coursegroup')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.studentprofile')),
            ],
            options={
                'unique_together': {('student', 'course_group')},
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_type', models.CharField(choices=[('quiz', 'Quiz'), ('exam', 'Examen'), ('assignment', 'Tarea'), ('participation', 'Participación'), ('project', 'Proyecto')], max_length=20)),
                ('subject', models.CharField(max_length=100)),
                ('obtained_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='courses.enrollment')),
            ],
        ),
        migrations.AddField(
            model_name='coursegroup',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.period'),
        ),
        migrations.AddField(
            model_name='coursegroup',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacherprofile'),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('subject', models.CharField(max_length=100)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.classroom')),
                ('course_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='courses.coursegroup')),
            ],
            options={
                'unique_together': {('course_group', 'day_of_week', 'start_time')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='coursegroup',
            unique_together={('course', 'period', 'name')},
        ),
    ]
